language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

install:
  - composer install --dev --prefer-source

before_script:
  - mkdir -p build/logs

script:
  - php vendor/bin/phpcs --standard=PSR2 src/ tests/
  - php vendor/bin/phpmd src/,tests/ text codesize,controversial,design,naming,unusedcode
  - php vendor/bin/phpcpd src/ tests/
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
